services:
  postgres:
    image: postgres:14.6
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  db-data:
    driver: local
